pipeline {
    agent none
    stages {
        stage('Show environment') {
            agent any
            steps {
                sh 'ls'
                sh 'ls ..'
            }
        }
        stage('Download UE4.22') {
            agent any
            steps{
                echo 'Downloading...'
            }
        }
        stage('Build Docker Image') {
            agent {
                dockerfile {
                    filename 'Dockerfile'
                    dir '.ci'
                }
            }
            steps {
                sh 'git --version'
            }
        }
    }
}
