pipeline {
    agent none
    stages {
        stage('Build Docker Image') {
            agent {
                dockerfile {
                    filename 'Dockerfile'
                    dir '.ci'
                }
            }
            steps {
                sh 'git --version'
            }
        }
    }
}
