pipeline {
    agent none
    stages {
        stage('Build Docker Image') {
            agent {
                filename 'Dockerfile'
                dir '.ci'
                label 'ue4.22/ubuntu-18.04'
            }
            steps {
                sh 'git --version'
            }
        }
    }
}
